media_duplicates.settings:
  type: config_object
  label: 'Media duplicates config'
  mapping:
    restrict_duplicates:
      type: bool
      label: 'Restrict duplicates'
    restrict_new_media_only:
      type: bool
      label: 'Restrict new media only'
